apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-secure-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thisiskartik/argocd-sops
    targetRevision: main
    path: example-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true