apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  helm.valuesFileSchemes: >-
    secrets+age-import, secrets+age-import-kubernetes,
    secrets, secrets+literal, https